packages:
  - packages/*

onlyBuiltDependencies:
  - '@asyncapi/cli'
  - '@hyperjump/json-pointer'
  - '@hyperjump/json-schema'
  - '@hyperjump/json-schema-core'
  - '@hyperjump/pact'
  - '@scarf/scarf'
  - esbuild
  - protobufjs
  - puppeteer
  - yarn
